init_rand_seed: 0
train_loader:
  batch_size: 256
validation_loader:
  batch_size: 16
output_folder: ./ckpt/mamba_csi_person_in3d

seed: 42
dataset_root: data/person_in_wifi_3d
batch_size: 64   # metafi:32, hpeli:32 
max_device_batch_size: 256
base_learning_rate: 0.001
total_epoch: 200   # 200
dataset_name: person-in-wifi-3d
setting: three-person
num_person: 3
experiment_name: mamba_csi
training_semi: False
pretrained_model_path: null
save_path: pose_weights
